### ISSUE TITLE
7. LearnedFTL: A Learning-based Page-level FTL for Reducing Double Reads in Flash-based SSDs

### ISSUE THREAD

**Issue by min-seong-kim** [DKU-StarLab/SolidStateSquad#10]
Motivation
기존 플래시 기반 SSD에서 랜덤 읽기 작업 시 자주 발생하는 주소 변환으로 인한 "double read" 문제를 해결하기 위해 제안되었다.

Proposal
Address translation 효율을 높이기 위해 learned index 사용하였다.
그리고 효율적인 model 학습을 위해 Virtual PPN을 사용해 연속적인 LPN에 연속적인 VPPN을 할당하였다. Group-based allocation과 GC/rewrite를 통한 model training을 사용해 training overhead 감소하였다.

Results
FEMU 기반 프로토타입에 대한 광범위한 실험 결과, LearnedFTL은 주소 변환으로 인한 이중 읽기를 최대 55.5%까지 줄일 수 있는 것으로 나타났다. 그 결과, LearnedFTL은 최신 TPFTL 및 LeaFTL 방식에 비해 P99 테일 레이턴시를 각각 평균 5.5배, 8.2배로 2.9배 ∼ 12.2배까지 줄였습니다.

**Comment by sujipark01** [comment]
다양한 워크로드에서 LeaFTL보다 좋은 성능을 보였는데 반대로 LeaFTL이 좋은 성능을 보이는 환경이 있을까요?

**Comment by min-seong-kim** [comment]
> 다양한 워크로드에서 LeaFTL보다 좋은 성능을 보였는데 반대로 LeaFTL이 좋은 성능을 보이는 환경이 있을까요?

동일한 메모리 사용량을 가정하였을 경우 LeafTL이 적절한 Hit ratio를 가진다면 LearnFTL에 비해 좋은 성능을 보일 것 같습니다.

**Comment by kbskbs1102** [comment]
in-place 모델 업데이트를 할 때 언제 트리거되는지, victim 세그먼트를 정하는 기준이 있는지 궁금합니다.

**Comment by min-seong-kim** [comment]
> in-place 모델 업데이트를 할 때 언제 트리거되는지, victim 세그먼트를 정하는 기준이 있는지 궁금합니다.

LearnedFTL에서 in-place 모델 업데이트는 데이터 패턴이 변경되어 더 이상 기존 모델이 정확하게 예측하지 못할 경우, valid한 데이터의 비율이 감소할 경우 트리거됩니다. Victim 세그먼트는 주로 valid한 데이터 비율, 세그먼트의 수명 등의 기준을 바탕으로 선택됩니다.
