### ISSUE TITLE
8. Leaftl: A learning-based flash translation layer for solid-state drives

### ISSUE THREAD

**Issue by WIRYEFARMER** [DKU-StarLab/SolidStateSquad#11]
Motivation
SSD에서 플래시 페이지 인덱싱은 데이터 접근 성능과 DRAM을 효율적으로 사용하는 중요한 요소이다. 기존의 주소 매핑 방식은 대부분 휴리스틱 기반으로 연구되어 런타임에서 동적 데이터 접근 패턴을 포착하지 못한다.
따라서 다양한 데이터 접근 패턴을 학습하여 동적으로 적응하는 새로운 방식을 필요로 하게된다.
Proposal
LeaFTL은 런타임에서 Linear Regression을 통해 학습 기반 주소 매핑 FTL이다.
대량의 매핑 항목을 학습된 세그먼트로 그룹화하여 address mapping table의 메모리 풋프린트를 크게 줄인다. LeaFTL은 misprediction을 처리하는 메커니즘을 도입하여, 플래시 페이지의 OOB를 사용해 데이터 접근의 정확성을 검증한다.
LeaFTL은 다양한 최적화 기법을 사용하여 SSD 컨트롤러의 DRAM 캐싱 효율성을 극대화시킨다.
Results
DFTL,SFTL과 LeaFTL과 비교했을 때, 매핑 테이블의 메모리 소비를 평균 2.9배 줄였으며, 저장성능을 1.4배 향상시켰다.
LeaFTL은 메모리 공간 절약을 통해 SSD DRAM의 활용도가 증가하였다.

**Comment by yeojin5** [comment]
최종적으로 compaction하게 되면 segment들의 range가 잘게 쪼개지게 되는데 이 경우에, range를 다시 합치는 과정을 거치며 segment의 개수를 적게 만드는 것이 이득인가요 혹은 합치치 않는 것이 이득인가요?

**Comment by neokkk** [comment]
GTD에서 그룹에 필요한 페이지 용량이 부족한 경우, 어떻게 기존과 연속적인 블록 영역을 할당할 수 있나요?

**Comment by min-seong-kim** [comment]
CRB는 단순 approximate segment를 저장만 하는 용도인지 아니면 flash memory까지 저장될까요?
