### ISSUE TITLE
1. The Design and Implementation of  a Log-Structured File System

### ISSUE THREAD

**Issue by neokkk** [DKU-StarLab/SolidStateSquad#3]
### Motivation
디스크의 random I/O 성능이 매우 나쁜데, FFS와 같은 현존하는 파일시스템은 매우 작은 synchronous random write를 유발한다.

### Proposal
write buffering, append-only approach를 사용하는 LFS를 제안한다. 이를 통해 모든 쓰기를 sequential, asynchronous, one large operation으로 만든다. free space 관리를 위해 segment 단위를 사용하며, invalid data를 정리하기 위해 segment cleaning 과정이 요구된다. segment 선택 시 cost-benefit 정책을 따른다.

### Results
FFS와 비교하여, 큰 파일 읽기를 제외한 모든 워크로드에서 우수한 성능을 보인다.

**Comment by min-seong-kim** [comment]
Figure 5에서 두 그래프 사이에 Fraction of segments의 차이가 크게 발생하는 이유가 무엇입니까?

**Comment by day-e0n** [comment]
Segment Summary Block이 각 Segment에 있는데, 데이터 블록을 찾을 때 이 Segment들의 Summary Block을 다 봐야되는 건가요 ?
LFS 특성 상 순차적으로 블록에 접근을 하게 되는데 제일 마지막에 위치한 Segment에 접근하려면 overhead가 너무 커지진 않을지 궁금합니다.

**Comment by yeojin5** [comment]
SSD에 LFS를 사용하게 된다면, WAF면에서 어떤 영향을 미치게 될까요?

**Comment by neokkk** [comment]
> SSD에 LFS를 사용하게 된다면, WAF면에서 어떤 영향을 미치게 될까요?

본 논문에서 제시하는 cost-benefit policy는 cleaning target segment로 utilization이 높은(valid 데이터가 많은) cold segment를 우선적으로 선정하기 때문에 다른 segment로 copy 시킬 데이터가 많다고 생각됩니다. 따라서 WAF가 많이 발생할 것으로 예상할 수 있으나, cold segment가 한 번 cleaning(reclaiming)되면, 다음 segment가 작성될 때까지 long-term이 걸리기 때문에 전체적인 관점에서 WAF는 그렇게 크지 않다고 합니다.

**Comment by neokkk** [comment]
> Segment Summary Block이 각 Segment에 있는데, 데이터 블록을 찾을 때 이 Segment들의 Summary Block을 다 봐야되는 건가요 ? LFS 특성 상 순차적으로 블록에 접근을 하게 되는데 제일 마지막에 위치한 Segment에 접근하려면 overhead가 너무 커지진 않을지 궁금합니다.

세미나 때 잘못 말씀드린 부분이 있는 것 같아 정리하겠습니다.

우선, **inode map은 메모리 상에 위치하며, 주기적으로 checkpoint가 발생하여 이를 disk에 쓰고 해당 위치를 checkpoint region에 업데이트 합니다.** 

write가 발생할 때, segment(in disk) 내부에 data block과 inode 블록이 쓰입니다. 이후 checkpoint가 발생하면 그 뒤로 inode map(in memory)의 복사본이 존재하게 됩니다. 따라서, inode map은 segment와 무관하게 모든 inode에 관한 정보를 포함하고 있으며, 만약 파일(데이터)을 찾는다고 하면 open 명령 수행 시(이름으로 inode 검색) 1) checkpoint region에 저장된 inode map의 위치로 간 다음, 2) 해당 이름을 가진 inode를 찾고 3) inode의 위치로 이동하는 과정을 거치게 됩니다.

결과적으로 데이터를 찾을 때 모든 segment를 순회하는 것이 아니며, segment summary block은 segment를 알 때 해당 segment가 어떤 파일에 속하는 지를 찾는 용도이지, 반대로 파일로부터 segment의 위치를 찾아가는 것은 아님을 유의해주시기 바랍니다.

**Comment by Student5421** [comment]
Segment 크기가 GC에 영향을 줄 수 있을거 같은데 Segment의 크기에 대한 tradeoff에 대해 어떻게 생각하시나요?
