### ISSUE TITLE
2. A Reconfigurable FTL (Flash Translation  Layer) Architecture for NAND Flash-Based  Applications

### ISSUE THREAD

**Issue by 9seon** [DKU-StarLab/SolidStateSquad#4]
### Motivation
다양한 NAND 플래시 메모리 애플리케이션(MP3 플레이어부터 PC의 SSD까지)의 특성을 반영하여 FTL의 성능을 최적화하고, 기존 FTL 아키텍처의 비효율성을 개선하고자 한다.

### Proposal
N(데이터 블록 그룹의 데이터 블록 수)과 K(로그 블록의 최대 수) 매개변수를 사용하는 Reconfigurable FTL 아키텍처를 도입하고, 최적의 N과 K 값을 찾기 위한 워크로드 분석 방법을 개발한다.

### Results
제안된 아키텍처는 실험을 통해 검증되었으며, 다양한 워크로드에 효율적으로 적응하고 MP3와 PC 애플리케이션 모두에 대해 성능을 향상시키는 최적의 N과 K 값을 식별한다.

**Comment by min-seong-kim** [comment]
Free block Pool에서 Free Block을 할당할 경우 외부 단편화를 고려해야합니까?

**Comment by kbskbs1102** [comment]
Random access pattern, sequential access pattern과 같은 접근 패턴이 temporal, spatial locality와 연관성이 있나요?

**Comment by WIRYEFARMER** [comment]
발표하신 논문은 하이브리드 매핑 방식을 사용하였는데요.

 하이브리드 매핑 방식은 페이지 단위 매핑과 블록 단위 매핑의 장점을 결합한 방식으로 이해 했습니다.

 이러한 방식을 사용할 때, 페이지 단위와 블록 단위 매핑 테이블을 동시에 관리하면서 발생하는 오버헤드나 레이턴시 증가 문제가 있지 않을까요?

**Comment by yeojin5** [comment]
PC 워크로드에서도 temporal locality를 확인할 수 있는 부분이 충분히 존재합니다. 하지만 K값은 MP3보다 훨씬 낮은 수치가 나오는데, 왜 이러한 결과가 나오는지 설명해주세요

**Comment by 9seon** [comment]
> Free block Pool에서 Free Block을 할당할 경우 외부 단편화를 고려해야합니까?

해당 논문에서 Free Block은 고정 크기의 블록이어서 단편화 문제가 발생하지 않습니다.

**Comment by JustYOLO** [comment]
발표한 논문에서 실제로 FTL을 구현하지는 않았는데, 논문에서 주장한 모델을 실제 구현한 사례가 있나요?

**Comment by neokkk** [comment]
제안하는 방식의 계산 복잡도 및 구현 가능성에 대한 의문에도 불구하고 본 논문이 제공하는 유의미한 결과는 무엇인가요?

**Comment by sujipark01** [comment]
> Random access pattern, sequential access pattern과 같은 접근 패턴이 temporal, spatial locality와 연관성이 있나요?

Sequential access pattern은 순차적인 접근이므로 spatial locality와 깊은 관련이 있으나 Random access pattern의 경우에는 temporal locality와 깊은 관련이 있지는 않으나 서로 영향을 미치지 않는다고 표현할 수도 없는 관계입니다.

**Comment by sujipark01** [comment]
> 발표하신 논문은 하이브리드 매핑 방식을 사용하였는데요.
> 
> 하이브리드 매핑 방식은 페이지 단위 매핑과 블록 단위 매핑의 장점을 결합한 방식으로 이해 했습니다.
> 
> 이러한 방식을 사용할 때, 페이지 단위와 블록 단위 매핑 테이블을 동시에 관리하면서 발생하는 오버헤드나 레이턴시 증가 문제가 있지 않을까요?

결론부터 말씀드리면 하이브리드 방식은 BLock Map Table과 함께 별도의 Log Block Page Map Table을 사용하기 때문에 기존의 방식보다 오버헤드가 발생합니다. Log Block Page Map Table을 관리하는 오버헤드보다도 Block 단위의 매핑 테이블이라는 점이 더 큰 오버헤드의 요인입니다.

**Comment by sujipark01** [comment]
> 실험부분에서, PC 워크로드에서도 temporal locality를 확인할 수 있는부분이 충분히 존재한다. 하지만 K값은 MP3보다 훨씬 낮은 수치가 나옵니다. 왜 이러한 결과가 나오는지 설명해주세요

PC는 접근 패턴에서 요청이 많은 active한 로그 그룹을 고르도록 접근하기 때문의 파셜디가 1에 가까워지기 때문입니다.
반면 MP3는 요청이 적은 수의 Block을 사용하기 때문에 파셜디가 0에 가까워지는 차이로 K값의 차이를 보이게 됩니다.

**Comment by sujipark01** [comment]
> 제안하는 방식의 계산 복잡도 및 구현 가능성에 대한 의문에도 불구하고 본 논문이 제공하는 유의미한 결과는 무엇인가요?

PC와 MP3 application의 특성을 그래프로 표현하여 Random, sequential access pattern, locality를 보이고, 그의 특성에 맞는 최적화된 N,K의 값을 유연하게 찾을 수 있는 식을 제시하였으며, 그에 알맞은 N,K의 후보값을 보인 것이 본 논문이 유의미하다는 것을 보여준다고 생각합니다.

**Comment by sujipark01** [comment]
> 발표한 논문에서 실제로 FTL을 구현하지는 않았는데, 논문에서 주장한 모델을 실제 구현한 사례가 있나요?

부분적인 구현을 보인 논문은 있으나 본 논문에서 주장한 유연한 N,K의 값의 변화로 이룬 최적화 사례는 구현이 복잡하여 아직 사례가 없는 것으로 확인했습니다.
