### ISSUE TITLE
4. Design Tradeoffs for SSD Performance

### ISSUE THREAD

**Issue by min-seong-kim** [DKU-StarLab/SolidStateSquad#5]
### Motivation
이 논문은 SSD의 다양한 디자인이 성능에 어떠한 영향을 미치는지 이해하기 위해 SSD의 여러 구성 요소와 설계 방식을 탐구하는 것을 목적으로 한다.
### Proposal
SSD 성능을 평가하기 위한 여러 시뮬레이션 환경을 제안하며 cleaning efficiency, wear-leveling, load balance, interleaving 및 ganging 같은 요소들을 설명한다. 또한 SSD의 수명을 확장하기 위해 새 wear-leveling 알고리즘을 제안하였다.
### Results
다양한 워크로드에서 실험을 진행한 결과, 여러 디자인 기술들에서 trade off가 발생한 것을 발견할 수 있었고 wear-leveling 알고리즘은 특정 조건에서 SSD의 성능과 수명을 효과적으로 향상시킬 수 있었다.

**Comment by sujipark01** [comment]
논문에서 plane 0과1 , 2와3끼리의 pair로서의 실행은 가능하나 교차로는 불가하다고 설명하였는데, 그 이유가 무엇인가요?

**Comment by min-seong-kim** [comment]
> 논문에서 plane 0과1 , 2와3끼리의 pair로서의 실행은 가능하나 교차로는 불가하다고 설명하였는데, 그 이유가 무엇인가요?

교차 인터리빙은 전송 경로의 복잡성을 증가시키고 효율성을 떨어뜨릴 수 있기 때문입니다.

**Comment by yeojin5** [comment]
plane 간의 interleaving을 이용하여 RAID를 구현한다면 어디서 이득을 취하고, 어디서 obstacle이 발생할까요?

**Comment by min-seong-kim** [comment]
> plane 간의 interleaving을 이용하여 RAID를 구현한다면 어디서 이득을 취하고, 어디서 obstacle이 발생할까요?

플레인 간 인터리빙을 활용한 RAID에서 여러 플레인을 동시에 읽고 쓸 수 있어 데이터 처리 속도가 향상되고 분산되는 데이터를 병렬로 전송할 수 있습니다. 하지만 RAID에서 인터리빙을 관리하기 위해 추가적인 제어 논리와 내부 핀이 필요하고 플레인 간 동기화를 유지하는 데 많은 비용이 들어가는 문제점을 고려해야 합니다.
