### ISSUE TITLE
관심 분야

### ISSUE THREAD

**Issue by 2reenact** [DKU-StarLab/SolidStateSquad#9]
* 가장 재밌게 읽었던 논문 3편과 해보고 싶은 연구 3가지 작성
* 아이디어가 확실하지 않으면 읽었던 논문에서 확장 방향으로 작성
* 또는 읽었던 논문들에서 다루지 않았지만 시도해보고 싶은 아이디어
* 이전에 논문의 약점이라 생각했던 내용을 참고하면 좋을 듯~

예시)
재밌는 논문
1. DFTL
2. LeaFTL
3. Design tradeoffs for SSD Performance

관심분야
1. DFTL에서 CMT 히트율 개선
2. Learned Index에 알맞은 페이지 할당 알고리즘
3. WAF를 위한 데이터 특성 인지 Learned Index

**Comment by JustYOLO** [comment]
재미있었던 논문:
1. We Ain't Afraid of No File Fragmentation
2. Design tradeoffs for SSD performance
3. DFTL

관심분야:

1. SSD에서 2개의 동일한 Flash Package를 하나의 Controller가 관리하여 RAID 1으로 구성하는 방법
2. LearnedFTL, LeaFTL에서의 하드웨어 사용량 분석 (DRAM usage, CPU utilization)
3. DRAM-less SSD의 구성과 한계 및 극복 방법 (NVMe의 Host Memory Buffer 등)

**Comment by min-seong-kim** [comment]
재미있었던 논문:

1. Design tradeoffs for SSD performance
2. LeaFTL
3. LearnedFTL

관심분야:

1. SSD 아키텍쳐를 고려하여 LearnedFTL에서 PPN을 VPPN으로 변환하는 과정에서 LPN과 연관된 PPN들의 주소 변환을 더 합리적으로 구성하는 방법
2. LearnedFTL에서 새로운 모델 트레이닝 트리거(ex. 모델의 <k,b,off> 에서 slope: k가 임계값 이상으로 급격하게 상승한 경우 즉시 트레이닝)
3. 여러 FTL에서 워크로드 별 CMT hit ratio와 Model hit ratio의 관계

**Comment by neokkk** [comment]
재밌었던 논문:
1. Design Tradeoffs for SSD Reliability
2. MiDAS: Minimizing Write Amplification in Log-Structured Systems through Adaptive Group Number and Size Configuration
3. LeaFTL: A Learning-Based Flash Translation Layer for Solid-State Drives

관심 분야:
1. 벡터 워크로드 최적 mapping policy
2. 벡트 워크로드 최적 data placement/in-storage processing
3. Learning-based FTL의 memory footprint 절감 (을 위한 GC policy)

**Comment by day-e0n** [comment]
재미있었던 논문:

1. Design tradeoffs for SSD performance
2. MiDAS: Minimizing Write Amplification in Log-Structured Systems through Adaptive Group Number and Size Configuration
3. DFTL: A Flash Translation Layer Employing Demand-based Selective Caching of Page-level Address Mappings

관심분야:

1. SSD 성능 최적화를 위한 효과적인 웨어 레벨링 정책
2. 랜덤 워크로드를 위한 강력한 FTL 설계
3. 특정 워크로드에 최적화된 GC 임계값 조정

**Comment by Student5421** [comment]
재미있었던 논문:
1. FlashGNN: An In-SSD Accelerator for GNN Training
2. Design tradeoffs for SSD Reliability
3. Design tradeoffs for SSD Performance

관심 분야:
1. SSD Training
2. FTL에서 Learned Index의 tradeoff 분석
3. Reliability 관점에서 FTL의 Learned Index 활용

**Comment by sujipark01** [comment]
재밌었던 논문:

1. MiDAS: Minimizing Write Amplification in Log-Structured Systems through Adaptive Group Number and Size Configuration
2. LearnedFTL
3. LeaFTL

관심 분야:

1. 다양한 FTL에서의 최적의 GC정책
2. LeaFTL과 LearnedFTL tradeoff
3. 다른 FTL에 Learned Index 적용 가능성

**Comment by kbskbs1102** [comment]
재미있었던 논문:

1. DFTL: A Flash Translation Layer Employing Demand-based Selective Caching of Page-level Address Mappings
2. MIDAS: Minimizing Write Amplification in Log-Structured Systems through Adaptive Group Number and Size Configuration
3. LearnedFTL: A Learning-Based Page-Level FTL for Reducing Double Reads in Flash-Based SSDs

관심 분야:

1. AI 학습 데이터 특성에 알맞은 SSD
2. SSD의 아키텍쳐 구성에 맞는 데이터 배치, ex) 3D NAND 플래시의 인접한 셀들의 접근으로 인한 에러 발생률 저하시키기
3. 차세대  SSD, ex)CXL-SSD, FDP-SSD

**Comment by 9seon** [comment]
재미있었던 논문:

1. DFTL: A Flash Translation Layer Employing Demand-based Selective Caching of Page-level Address Mappings
2. A Reconfigurable FTL (Flash Translation Layer) Architecture for NAND Flash-Based Applications
3. MIDAS: Minimizing Write Amplification in Log-Structured Systems through Adaptive Group Number and Size Configuration

관심 분야:

1. 랜덤 워크로드에서 CMT 히트율 개선 방법
2. DFTL에서 WAF 개선
3. 효율적인 GC 정책

**Comment by WIRYEFARMER** [comment]
재밌었던 논문
1. LeaFTL: A Learning-Based Flash Translation Layer for Solid-State Drives
2. DFTL: A Flash Translation Layer Employing Demand-based Selective Caching of Page-level Address Mappings
3. Design tradeoffs for SSD performance

관심 분야
1. 벡터DB에 특화된 FTL 구축
2. Hot/Cold 데이터를 처리하는 방식을 개선하여 Wear leveling 개선
3. 로그 구조에서 컴팩션을 최적화를 통한 memory 사용량 개선

**Comment by yeojin5** [comment]
재밌었던 논문:

  1. MiDAS: Minimizing Write Amplification in Log-Structured Systems through Adaptive Group Number and Size Configuration
  2. Design tradeoffs for SSD reliability
  3. The design and implementation of a log-structured file system

관심 분야:
  
  1. cold data의 양과 크기가 늘어남에 따라 데이터의 배치와 빠른 읽기가 중요해지고 있다. 따라서 application혹은 data의 특징을 통해 ZNS or FDP에서의 효율적인 데이터 배치에 관심이 있다. 
  2. 3D NAND Flash는 셀의 온도에 따라 읽기, 쓰기 등의 성능 차이가 크다. 이러한 특성을 반영한 SSD control에 관심이 있다.
  3. 3D NAND Flash는 2D NAND Flash와 구조적인 차이에서부터 큰 차이가 있으며, error bit가 잦게 발생하고, 수명이 짧다는 단점을 가지고있다. 이는 일반적인 FTL의 데이터 배치와는 다른 관점으로 바라봐야할 필요가 있음을 느꼈으며 이에 맞는 데이터 배치 정책에 관심이 있다.

**Comment by busanlinux** [comment]
1. DFTL
2. MIDAS
3. LSFS

1. page-level mapping 구현시 메모리 overhead 감소를 위한 최적화 연구
2.  최적의 GC 정책 연구
3.  선행 연구된 기초 페이지 매핑 기반 개선 연구
